-- ============================================================================
-- V3 — Reference data (Phase 2A)
--
-- Normalized geography and language vocabularies. This migration is PURELY
-- ADDITIVE: nothing in the existing schema references these tables yet. The
-- links from `users` and `lawyers` arrive in a later phase, deliberately, so
-- this one can be deployed and rolled back on its own.
--
-- Design notes:
--
--   * `name_normalized` is the canonical lookup key: diacritics stripped,
--     lowercased, whitespace collapsed. It is what makes UNIQUE meaningful -
--     without it "Mumbai" and "mumbai " are two distinct rows. Generated by
--     TextNormalizer in the application layer; the values seeded below were
--     produced by the identical rule.
--
--   * `city_aliases` carries historical and colloquial names (Bombay, Calcutta,
--     Bangalore, Gurgaon...). India renamed many cities and both forms remain
--     in daily use, so without this a client typing "Bangalore" would find
--     nothing. It doubles as the mapping table for the later backfill of the
--     existing free-text `lawyers.city` column.
--
--   * Rows are deactivated (`active = false`), never deleted. Foreign keys are
--     ON DELETE RESTRICT so a city with lawyers attached cannot be removed.
--
--   * Only India is seeded. The `countries` table exists so the SHAPE supports
--     expansion; seeding 250 unusable countries would add dropdown entries that
--     lead nowhere. Adding one later is a single INSERT.
--
-- Type mapping follows V1: UUID -> uuid, String(len=N) -> varchar(N),
-- LocalDateTime -> timestamp(6), enum(STRING) -> varchar(255), boolean.
-- ============================================================================

-- Trigram matching powers city typeahead ("mumbay" -> "Mumbai"), which plain
-- equality and full-text stemming both fail at for short proper nouns.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ---------------------------------------------------------------- countries
CREATE TABLE countries (
    id          uuid          NOT NULL,
    created_at  timestamp(6)  NOT NULL,
    updated_at  timestamp(6)  NOT NULL,
    iso2        varchar(2)    NOT NULL,
    iso3        varchar(3)    NOT NULL,
    name        varchar(100)  NOT NULL,
    phone_code  varchar(8)    NOT NULL,
    active      boolean       NOT NULL DEFAULT true,
    CONSTRAINT pk_countries PRIMARY KEY (id),
    CONSTRAINT uq_countries_iso2 UNIQUE (iso2),
    CONSTRAINT uq_countries_iso3 UNIQUE (iso3)
);

-- ------------------------------------------------------------------- states
CREATE TABLE states (
    id               uuid          NOT NULL,
    created_at       timestamp(6)  NOT NULL,
    updated_at       timestamp(6)  NOT NULL,
    country_id       uuid          NOT NULL,
    code             varchar(10)   NOT NULL,
    name             varchar(100)  NOT NULL,
    name_normalized  varchar(100)  NOT NULL,
    type             varchar(255)  NOT NULL,
    active           boolean       NOT NULL DEFAULT true,
    CONSTRAINT pk_states PRIMARY KEY (id),
    CONSTRAINT uq_states_country_code UNIQUE (country_id, code),
    CONSTRAINT fk_states_country FOREIGN KEY (country_id)
        REFERENCES countries (id) ON DELETE RESTRICT
);

-- ------------------------------------------------------------------- cities
CREATE TABLE cities (
    id               uuid          NOT NULL,
    created_at       timestamp(6)  NOT NULL,
    updated_at       timestamp(6)  NOT NULL,
    state_id         uuid          NOT NULL,
    name             varchar(120)  NOT NULL,
    name_normalized  varchar(120)  NOT NULL,
    active           boolean       NOT NULL DEFAULT true,
    CONSTRAINT pk_cities PRIMARY KEY (id),
    -- Scoped to the state, not global: "Aurangabad" exists in more than one.
    CONSTRAINT uq_cities_state_name UNIQUE (state_id, name_normalized),
    CONSTRAINT fk_cities_state FOREIGN KEY (state_id)
        REFERENCES states (id) ON DELETE RESTRICT
);

-- ------------------------------------------------------------- city_aliases
CREATE TABLE city_aliases (
    id                uuid          NOT NULL,
    created_at        timestamp(6)  NOT NULL,
    updated_at        timestamp(6)  NOT NULL,
    city_id           uuid          NOT NULL,
    alias             varchar(120)  NOT NULL,
    alias_normalized  varchar(120)  NOT NULL,
    source            varchar(255)  NOT NULL,
    CONSTRAINT pk_city_aliases PRIMARY KEY (id),
    -- Deliberately NOT globally unique: one historical name can legitimately
    -- resolve to several cities, and search disambiguates by showing the state.
    CONSTRAINT uq_city_aliases_city_alias UNIQUE (city_id, alias_normalized),
    CONSTRAINT fk_city_aliases_city FOREIGN KEY (city_id)
        REFERENCES cities (id) ON DELETE RESTRICT
);

-- ---------------------------------------------------------------- languages
CREATE TABLE languages (
    id           uuid          NOT NULL,
    created_at   timestamp(6)  NOT NULL,
    updated_at   timestamp(6)  NOT NULL,
    iso_code     varchar(3)    NOT NULL,
    name         varchar(60)   NOT NULL,
    native_name  varchar(60)   NOT NULL,
    active       boolean       NOT NULL DEFAULT true,
    CONSTRAINT pk_languages PRIMARY KEY (id),
    CONSTRAINT uq_languages_iso_code UNIQUE (iso_code),
    CONSTRAINT uq_languages_name UNIQUE (name)
);

-- ------------------------------------------------------------------ indexes
CREATE INDEX idx_states_country       ON states (country_id);
CREATE INDEX idx_cities_state         ON cities (state_id);
CREATE INDEX idx_city_aliases_city    ON city_aliases (city_id);

-- Typeahead. GIN + trigram rather than btree: the query is similarity/ILIKE
-- on a partial term, which a btree cannot serve.
CREATE INDEX idx_cities_name_trgm
    ON cities USING gin (name_normalized gin_trgm_ops);
CREATE INDEX idx_city_aliases_alias_trgm
    ON city_aliases USING gin (alias_normalized gin_trgm_ops);

-- ============================================================================
-- SEED — India
-- Generated from a curated dataset; `name_normalized` computed by the same
-- rule TextNormalizer applies at runtime.
-- ============================================================================

INSERT INTO countries (id, created_at, updated_at, iso2, iso3, name, phone_code, active) VALUES
    (gen_random_uuid(), now(), now(), 'IN', 'IND', 'India', '+91', true);

INSERT INTO states (id, created_at, updated_at, country_id, code, name, name_normalized, type, active) VALUES
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'AP', 'Andhra Pradesh', 'andhra pradesh', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'AR', 'Arunachal Pradesh', 'arunachal pradesh', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'AS', 'Assam', 'assam', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'BR', 'Bihar', 'bihar', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'CG', 'Chhattisgarh', 'chhattisgarh', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'GA', 'Goa', 'goa', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'GJ', 'Gujarat', 'gujarat', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'HR', 'Haryana', 'haryana', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'HP', 'Himachal Pradesh', 'himachal pradesh', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'JH', 'Jharkhand', 'jharkhand', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'KA', 'Karnataka', 'karnataka', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'KL', 'Kerala', 'kerala', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'MP', 'Madhya Pradesh', 'madhya pradesh', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'MH', 'Maharashtra', 'maharashtra', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'MN', 'Manipur', 'manipur', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'ML', 'Meghalaya', 'meghalaya', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'MZ', 'Mizoram', 'mizoram', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'NL', 'Nagaland', 'nagaland', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'OD', 'Odisha', 'odisha', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'PB', 'Punjab', 'punjab', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'RJ', 'Rajasthan', 'rajasthan', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'SK', 'Sikkim', 'sikkim', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'TN', 'Tamil Nadu', 'tamil nadu', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'TS', 'Telangana', 'telangana', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'TR', 'Tripura', 'tripura', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'UP', 'Uttar Pradesh', 'uttar pradesh', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'UK', 'Uttarakhand', 'uttarakhand', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'WB', 'West Bengal', 'west bengal', 'STATE', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'AN', 'Andaman and Nicobar Islands', 'andaman and nicobar islands', 'UNION_TERRITORY', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'CH', 'Chandigarh', 'chandigarh', 'UNION_TERRITORY', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'DH', 'Dadra and Nagar Haveli and Daman and Diu', 'dadra and nagar haveli and daman and diu', 'UNION_TERRITORY', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'DL', 'Delhi', 'delhi', 'UNION_TERRITORY', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'JK', 'Jammu and Kashmir', 'jammu and kashmir', 'UNION_TERRITORY', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'LA', 'Ladakh', 'ladakh', 'UNION_TERRITORY', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'LD', 'Lakshadweep', 'lakshadweep', 'UNION_TERRITORY', true),
    (gen_random_uuid(), now(), now(), (SELECT id FROM countries WHERE iso2 = 'IN'), 'PY', 'Puducherry', 'puducherry', 'UNION_TERRITORY', true);

INSERT INTO cities (id, created_at, updated_at, state_id, name, name_normalized, active) VALUES
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AP'), 'Amaravati', 'amaravati', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AP'), 'Visakhapatnam', 'visakhapatnam', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AP'), 'Vijayawada', 'vijayawada', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AP'), 'Guntur', 'guntur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AP'), 'Nellore', 'nellore', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AP'), 'Kurnool', 'kurnool', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AP'), 'Tirupati', 'tirupati', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AP'), 'Rajahmundry', 'rajahmundry', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AP'), 'Kakinada', 'kakinada', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AP'), 'Anantapur', 'anantapur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AR'), 'Itanagar', 'itanagar', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AR'), 'Naharlagun', 'naharlagun', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AS'), 'Guwahati', 'guwahati', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AS'), 'Dispur', 'dispur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AS'), 'Silchar', 'silchar', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AS'), 'Dibrugarh', 'dibrugarh', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AS'), 'Jorhat', 'jorhat', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AS'), 'Nagaon', 'nagaon', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AS'), 'Tezpur', 'tezpur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'BR'), 'Patna', 'patna', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'BR'), 'Gaya', 'gaya', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'BR'), 'Bhagalpur', 'bhagalpur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'BR'), 'Muzaffarpur', 'muzaffarpur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'BR'), 'Darbhanga', 'darbhanga', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'BR'), 'Purnia', 'purnia', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'BR'), 'Ara', 'ara', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'BR'), 'Begusarai', 'begusarai', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'CG'), 'Raipur', 'raipur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'CG'), 'Bilaspur', 'bilaspur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'CG'), 'Durg', 'durg', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'CG'), 'Bhilai', 'bhilai', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'CG'), 'Korba', 'korba', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'CG'), 'Raigarh', 'raigarh', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'GA'), 'Panaji', 'panaji', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'GA'), 'Margao', 'margao', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'GA'), 'Vasco da Gama', 'vasco da gama', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'GA'), 'Mapusa', 'mapusa', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'GJ'), 'Ahmedabad', 'ahmedabad', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'GJ'), 'Gandhinagar', 'gandhinagar', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'GJ'), 'Surat', 'surat', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'GJ'), 'Vadodara', 'vadodara', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'GJ'), 'Rajkot', 'rajkot', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'GJ'), 'Bhavnagar', 'bhavnagar', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'GJ'), 'Jamnagar', 'jamnagar', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'GJ'), 'Junagadh', 'junagadh', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'GJ'), 'Anand', 'anand', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'GJ'), 'Bharuch', 'bharuch', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'HR'), 'Gurugram', 'gurugram', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'HR'), 'Faridabad', 'faridabad', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'HR'), 'Panipat', 'panipat', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'HR'), 'Ambala', 'ambala', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'HR'), 'Hisar', 'hisar', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'HR'), 'Rohtak', 'rohtak', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'HR'), 'Karnal', 'karnal', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'HR'), 'Sonipat', 'sonipat', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'HR'), 'Panchkula', 'panchkula', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'HP'), 'Shimla', 'shimla', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'HP'), 'Dharamshala', 'dharamshala', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'HP'), 'Mandi', 'mandi', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'HP'), 'Solan', 'solan', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'HP'), 'Kullu', 'kullu', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'HP'), 'Manali', 'manali', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'JH'), 'Ranchi', 'ranchi', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'JH'), 'Jamshedpur', 'jamshedpur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'JH'), 'Dhanbad', 'dhanbad', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'JH'), 'Bokaro Steel City', 'bokaro steel city', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'JH'), 'Hazaribagh', 'hazaribagh', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'JH'), 'Deoghar', 'deoghar', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KA'), 'Bengaluru', 'bengaluru', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KA'), 'Mysuru', 'mysuru', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KA'), 'Mangaluru', 'mangaluru', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KA'), 'Hubballi', 'hubballi', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KA'), 'Dharwad', 'dharwad', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KA'), 'Belagavi', 'belagavi', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KA'), 'Kalaburagi', 'kalaburagi', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KA'), 'Davanagere', 'davanagere', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KA'), 'Shivamogga', 'shivamogga', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KA'), 'Tumakuru', 'tumakuru', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KL'), 'Thiruvananthapuram', 'thiruvananthapuram', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KL'), 'Kochi', 'kochi', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KL'), 'Ernakulam', 'ernakulam', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KL'), 'Kozhikode', 'kozhikode', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KL'), 'Thrissur', 'thrissur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KL'), 'Kollam', 'kollam', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KL'), 'Alappuzha', 'alappuzha', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KL'), 'Kannur', 'kannur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KL'), 'Palakkad', 'palakkad', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KL'), 'Kottayam', 'kottayam', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MP'), 'Bhopal', 'bhopal', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MP'), 'Indore', 'indore', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MP'), 'Jabalpur', 'jabalpur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MP'), 'Gwalior', 'gwalior', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MP'), 'Ujjain', 'ujjain', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MP'), 'Sagar', 'sagar', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MP'), 'Rewa', 'rewa', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MP'), 'Satna', 'satna', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MH'), 'Mumbai', 'mumbai', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MH'), 'Pune', 'pune', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MH'), 'Nagpur', 'nagpur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MH'), 'Nashik', 'nashik', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MH'), 'Thane', 'thane', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MH'), 'Navi Mumbai', 'navi mumbai', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MH'), 'Chhatrapati Sambhajinagar', 'chhatrapati sambhajinagar', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MH'), 'Solapur', 'solapur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MH'), 'Kolhapur', 'kolhapur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MH'), 'Amravati', 'amravati', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MH'), 'Nanded', 'nanded', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MH'), 'Sangli', 'sangli', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MH'), 'Jalgaon', 'jalgaon', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MN'), 'Imphal', 'imphal', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'ML'), 'Shillong', 'shillong', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MZ'), 'Aizawl', 'aizawl', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'NL'), 'Kohima', 'kohima', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'NL'), 'Dimapur', 'dimapur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'OD'), 'Bhubaneswar', 'bhubaneswar', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'OD'), 'Cuttack', 'cuttack', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'OD'), 'Rourkela', 'rourkela', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'OD'), 'Berhampur', 'berhampur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'OD'), 'Sambalpur', 'sambalpur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'OD'), 'Puri', 'puri', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'PB'), 'Ludhiana', 'ludhiana', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'PB'), 'Amritsar', 'amritsar', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'PB'), 'Jalandhar', 'jalandhar', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'PB'), 'Patiala', 'patiala', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'PB'), 'Bathinda', 'bathinda', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'PB'), 'Mohali', 'mohali', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'RJ'), 'Jaipur', 'jaipur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'RJ'), 'Jodhpur', 'jodhpur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'RJ'), 'Udaipur', 'udaipur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'RJ'), 'Kota', 'kota', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'RJ'), 'Ajmer', 'ajmer', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'RJ'), 'Bikaner', 'bikaner', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'RJ'), 'Alwar', 'alwar', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'RJ'), 'Bhilwara', 'bhilwara', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'SK'), 'Gangtok', 'gangtok', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TN'), 'Chennai', 'chennai', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TN'), 'Coimbatore', 'coimbatore', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TN'), 'Madurai', 'madurai', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TN'), 'Tiruchirappalli', 'tiruchirappalli', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TN'), 'Salem', 'salem', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TN'), 'Tirunelveli', 'tirunelveli', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TN'), 'Erode', 'erode', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TN'), 'Vellore', 'vellore', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TN'), 'Thanjavur', 'thanjavur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TN'), 'Tiruppur', 'tiruppur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TS'), 'Hyderabad', 'hyderabad', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TS'), 'Secunderabad', 'secunderabad', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TS'), 'Warangal', 'warangal', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TS'), 'Nizamabad', 'nizamabad', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TS'), 'Karimnagar', 'karimnagar', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TS'), 'Khammam', 'khammam', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TR'), 'Agartala', 'agartala', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UP'), 'Lucknow', 'lucknow', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UP'), 'Kanpur', 'kanpur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UP'), 'Prayagraj', 'prayagraj', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UP'), 'Varanasi', 'varanasi', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UP'), 'Agra', 'agra', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UP'), 'Meerut', 'meerut', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UP'), 'Noida', 'noida', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UP'), 'Ghaziabad', 'ghaziabad', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UP'), 'Bareilly', 'bareilly', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UP'), 'Aligarh', 'aligarh', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UP'), 'Moradabad', 'moradabad', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UP'), 'Gorakhpur', 'gorakhpur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UP'), 'Jhansi', 'jhansi', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UP'), 'Mathura', 'mathura', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UK'), 'Dehradun', 'dehradun', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UK'), 'Haridwar', 'haridwar', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UK'), 'Nainital', 'nainital', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UK'), 'Haldwani', 'haldwani', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UK'), 'Roorkee', 'roorkee', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UK'), 'Rishikesh', 'rishikesh', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'WB'), 'Kolkata', 'kolkata', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'WB'), 'Howrah', 'howrah', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'WB'), 'Siliguri', 'siliguri', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'WB'), 'Durgapur', 'durgapur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'WB'), 'Asansol', 'asansol', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'WB'), 'Darjeeling', 'darjeeling', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'WB'), 'Kharagpur', 'kharagpur', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AN'), 'Port Blair', 'port blair', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'CH'), 'Chandigarh', 'chandigarh', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'DH'), 'Daman', 'daman', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'DH'), 'Silvassa', 'silvassa', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'DH'), 'Diu', 'diu', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'DL'), 'Delhi', 'delhi', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'JK'), 'Srinagar', 'srinagar', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'JK'), 'Jammu', 'jammu', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'JK'), 'Anantnag', 'anantnag', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'JK'), 'Baramulla', 'baramulla', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'LA'), 'Leh', 'leh', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'LA'), 'Kargil', 'kargil', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'LD'), 'Kavaratti', 'kavaratti', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'PY'), 'Puducherry', 'puducherry', true),
    (gen_random_uuid(), now(), now(), (SELECT s.id FROM states s JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'PY'), 'Karaikal', 'karaikal', true);

INSERT INTO city_aliases (id, created_at, updated_at, city_id, alias, alias_normalized, source) VALUES
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MH' AND ct.name_normalized = 'mumbai'), 'Bombay', 'bombay', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'WB' AND ct.name_normalized = 'kolkata'), 'Calcutta', 'calcutta', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TN' AND ct.name_normalized = 'chennai'), 'Madras', 'madras', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KA' AND ct.name_normalized = 'bengaluru'), 'Bangalore', 'bangalore', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MH' AND ct.name_normalized = 'pune'), 'Poona', 'poona', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KL' AND ct.name_normalized = 'thiruvananthapuram'), 'Trivandrum', 'trivandrum', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KL' AND ct.name_normalized = 'kochi'), 'Cochin', 'cochin', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'GJ' AND ct.name_normalized = 'vadodara'), 'Baroda', 'baroda', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'GJ' AND ct.name_normalized = 'ahmedabad'), 'Amdavad', 'amdavad', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KA' AND ct.name_normalized = 'mysuru'), 'Mysore', 'mysore', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KA' AND ct.name_normalized = 'mangaluru'), 'Mangalore', 'mangalore', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KA' AND ct.name_normalized = 'belagavi'), 'Belgaum', 'belgaum', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KA' AND ct.name_normalized = 'hubballi'), 'Hubli', 'hubli', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KA' AND ct.name_normalized = 'kalaburagi'), 'Gulbarga', 'gulbarga', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KA' AND ct.name_normalized = 'shivamogga'), 'Shimoga', 'shimoga', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KA' AND ct.name_normalized = 'tumakuru'), 'Tumkur', 'tumkur', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'HR' AND ct.name_normalized = 'gurugram'), 'Gurgaon', 'gurgaon', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UP' AND ct.name_normalized = 'prayagraj'), 'Allahabad', 'allahabad', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UP' AND ct.name_normalized = 'kanpur'), 'Cawnpore', 'cawnpore', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UP' AND ct.name_normalized = 'varanasi'), 'Benares', 'benares', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'UP' AND ct.name_normalized = 'varanasi'), 'Banaras', 'banaras', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'PY' AND ct.name_normalized = 'puducherry'), 'Pondicherry', 'pondicherry', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'GA' AND ct.name_normalized = 'panaji'), 'Panjim', 'panjim', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'GA' AND ct.name_normalized = 'vasco da gama'), 'Vasco', 'vasco', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AS' AND ct.name_normalized = 'guwahati'), 'Gauhati', 'gauhati', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AP' AND ct.name_normalized = 'visakhapatnam'), 'Vizag', 'vizag', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AP' AND ct.name_normalized = 'visakhapatnam'), 'Waltair', 'waltair', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'AP' AND ct.name_normalized = 'rajahmundry'), 'Rajamahendravaram', 'rajamahendravaram', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TN' AND ct.name_normalized = 'tiruchirappalli'), 'Trichy', 'trichy', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TN' AND ct.name_normalized = 'thanjavur'), 'Tanjore', 'tanjore', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'TN' AND ct.name_normalized = 'tiruppur'), 'Tirupur', 'tirupur', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KL' AND ct.name_normalized = 'kozhikode'), 'Calicut', 'calicut', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KL' AND ct.name_normalized = 'kollam'), 'Quilon', 'quilon', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KL' AND ct.name_normalized = 'alappuzha'), 'Alleppey', 'alleppey', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KL' AND ct.name_normalized = 'thrissur'), 'Trichur', 'trichur', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KL' AND ct.name_normalized = 'palakkad'), 'Palghat', 'palghat', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'KL' AND ct.name_normalized = 'kannur'), 'Cannanore', 'cannanore', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MH' AND ct.name_normalized = 'nashik'), 'Nasik', 'nasik', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MH' AND ct.name_normalized = 'chhatrapati sambhajinagar'), 'Aurangabad', 'aurangabad', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MH' AND ct.name_normalized = 'navi mumbai'), 'New Bombay', 'new bombay', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'MP' AND ct.name_normalized = 'jabalpur'), 'Jubbulpore', 'jubbulpore', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'HP' AND ct.name_normalized = 'shimla'), 'Simla', 'simla', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'HP' AND ct.name_normalized = 'dharamshala'), 'Dharamsala', 'dharamsala', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'JH' AND ct.name_normalized = 'bokaro steel city'), 'Bokaro', 'bokaro', 'SEED'),
    (gen_random_uuid(), now(), now(), (SELECT ct.id FROM cities ct JOIN states s ON s.id = ct.state_id JOIN countries c ON c.id = s.country_id WHERE c.iso2 = 'IN' AND s.code = 'DL' AND ct.name_normalized = 'delhi'), 'New Delhi', 'new delhi', 'SEED');

INSERT INTO languages (id, created_at, updated_at, iso_code, name, native_name, active) VALUES
    (gen_random_uuid(), now(), now(), 'en', 'English', 'English', true),
    (gen_random_uuid(), now(), now(), 'hi', 'Hindi', 'हिन्दी', true),
    (gen_random_uuid(), now(), now(), 'bn', 'Bengali', 'বাংলা', true),
    (gen_random_uuid(), now(), now(), 'mr', 'Marathi', 'मराठी', true),
    (gen_random_uuid(), now(), now(), 'te', 'Telugu', 'తెలుగు', true),
    (gen_random_uuid(), now(), now(), 'ta', 'Tamil', 'தமிழ்', true),
    (gen_random_uuid(), now(), now(), 'gu', 'Gujarati', 'ગુજરાતી', true),
    (gen_random_uuid(), now(), now(), 'ur', 'Urdu', 'اردو', true),
    (gen_random_uuid(), now(), now(), 'kn', 'Kannada', 'ಕನ್ನಡ', true),
    (gen_random_uuid(), now(), now(), 'or', 'Odia', 'ଓଡ଼ିଆ', true),
    (gen_random_uuid(), now(), now(), 'ml', 'Malayalam', 'മലയാളം', true),
    (gen_random_uuid(), now(), now(), 'pa', 'Punjabi', 'ਪੰਜਾਬੀ', true),
    (gen_random_uuid(), now(), now(), 'as', 'Assamese', 'অসমীয়া', true),
    (gen_random_uuid(), now(), now(), 'mai', 'Maithili', 'मैथिली', true),
    (gen_random_uuid(), now(), now(), 'sa', 'Sanskrit', 'संस्कृतम्', true),
    (gen_random_uuid(), now(), now(), 'kok', 'Konkani', 'कोंकणी', true),
    (gen_random_uuid(), now(), now(), 'ne', 'Nepali', 'नेपाली', true),
    (gen_random_uuid(), now(), now(), 'mni', 'Manipuri', 'ꯃꯤꯇꯩꯂꯣꯟ', true),
    (gen_random_uuid(), now(), now(), 'sd', 'Sindhi', 'سنڌي', true),
    (gen_random_uuid(), now(), now(), 'doi', 'Dogri', 'डोगरी', true),
    (gen_random_uuid(), now(), now(), 'ks', 'Kashmiri', 'کٲشُر', true),
    (gen_random_uuid(), now(), now(), 'sat', 'Santali', 'ᱥᱟᱱᱛᱟᱲᱤ', true),
    (gen_random_uuid(), now(), now(), 'brx', 'Bodo', 'बड़ो', true);
