import { AlertTriangle, FileWarning } from "lucide-react";
import type { ReactNode } from "react";

import { Badge } from "@/components/ui/badge";
import type { DocumentAnalysis } from "@/types";

/**
 * Renders a completed analysis (AI-4).
 *
 * Every list is rendered as-is, INCLUDING WHEN EMPTY - an empty "Parties"
 * section reads as "the document names none", which is itself a finding the
 * backend went out of its way to distinguish from "the model didn't answer".
 * Hiding empty sections here would erase that distinction the API was built to
 * preserve.
 */
export function DocumentAnalysisPanel({
  analysis,
}: {
  analysis: DocumentAnalysis;
}) {
  return (
    <div className="space-y-5">
      {analysis.truncated ? (
        <div className="flex items-start gap-2 rounded-lg border border-warning/30 bg-warning/10 px-3 py-2 text-sm text-warning">
          <FileWarning className="mt-0.5 size-4 shrink-0" aria-hidden />
          <p>
            This document is longer than one analysis can cover in full. The
            summary below reflects only its leading portion.
          </p>
        </div>
      ) : null}

      <section className="space-y-1.5">
        <h3 className="text-sm font-semibold text-foreground">Summary</h3>
        <p className="text-sm leading-relaxed text-muted-foreground">
          {analysis.summary}
        </p>
      </section>

      <AnalysisList title="Parties" items={analysis.parties} />
      <AnalysisList title="Important dates" items={analysis.importantDates} />
      <AnalysisList title="Obligations" items={analysis.obligations} />
      <AnalysisList title="Key clauses" items={analysis.keyClauses} />
      <AnalysisList
        title="Risks"
        items={analysis.risks}
        emptyState={
          <p className="text-sm text-muted-foreground">
            No risks were identified in this document.
          </p>
        }
        icon={<AlertTriangle className="size-3.5 text-warning" aria-hidden />}
      />

      <p className="border-t border-border pt-3 text-xs text-muted-foreground">
        This is document-grounded assistance generated by AI, not legal
        advice. For anything that matters, consult a qualified advocate.
      </p>
    </div>
  );
}

function AnalysisList({
  title,
  items,
  emptyState,
  icon,
}: {
  title: string;
  items: string[];
  emptyState?: ReactNode;
  icon?: ReactNode;
}) {
  return (
    <section className="space-y-1.5">
      <h3 className="text-sm font-semibold text-foreground">{title}</h3>
      {items.length === 0 ? (
        emptyState ?? (
          <p className="text-sm text-muted-foreground">Not stated in this document.</p>
        )
      ) : (
        <ul className="space-y-1.5">
          {items.map((item, index) => (
            <li
              // Model output has no stable id; index is safe here because the
              // list is never reordered or edited in place.
              key={index}
              className="flex items-start gap-2 text-sm text-muted-foreground"
            >
              {icon ?? <Badge variant="outline" className="mt-0.5 size-1.5 rounded-full p-0" />}
              <span>{item}</span>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}
