spring:
  application:
    name: vakilconnect

  datasource:
    url: jdbc:postgresql://localhost:5432/vakilconnect
    username: arshraj
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  flyway:
    enabled: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: REPLACE_WITH_A_BASE64_SECRET
  expiration: 86400000